# Generated by Django 4.0.3 on 2022-04-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_grade_student_key_delete_student'),
        ('classes', '0002_course_coursedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quizes',
            field=models.ManyToManyField(to='questions.quiz'),
        ),
    ]
