# Generated by Django 4.0.3 on 2022-04-05 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_course_quizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Staff'}, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
