# Generated by Django 4.0.3 on 2022-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_grade_student_key_delete_student'),
        ('classes', '0004_course_professors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quizes',
            field=models.ManyToManyField(blank=True, to='questions.quiz'),
        ),
    ]
