# Generated by Django 4.0.3 on 2022-04-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_course_quizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseDescription',
        ),
    ]
