# Generated by Django 4.0.3 on 2022-04-05 13:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_course_coursedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
