# Generated by Django 4.0.3 on 2022-04-11 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_course_coursedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='uploaded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
