# Generated by Django 4.0.3 on 2022-04-24 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0010_remove_course_quizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
