# Generated by Django 4.0.3 on 2022-05-31 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_alter_courceannouncement_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courceannouncement',
            name='time_sent',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
