# Generated by Django 4.0.3 on 2022-05-31 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_alter_courceannouncement_time_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courceannouncement',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='uploaded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
