# Generated by Django 4.0.3 on 2022-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_choice_question_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=200)),
                ('questions', models.ManyToManyField(to='questions.question')),
            ],
        ),
    ]
