# Generated by Django 4.0.3 on 2022-04-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_course_quizes'),
        ('questions', '0005_alter_grade_student_key_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.course'),
        ),
    ]
