# Generated by Django 4.0.3 on 2022-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_quiz_duration_quiz_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
